# OpenAI secrets
OPENAI_API_KEY = "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"

# Astra DB secrets
ASTRA_API_ENDPOINT = "https://0e11c3d1-8416-4b50-a2a4-94c2c276ec9c-us-east1.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:woBAeDgNAhktMKcatNhoglJm:c9e37a6c6f1b9b923dca1b0042792a0cda64f2798f79f0e323d5e17fbddd3513"
